### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by joelwetzel** [biocomp/hubitat_ci#45]
Hello Artem,
  Is this project still being worked on?  No worries if not.  I'm really impressed with what you put together, and I'd like to make some contributions.  If you're still maintaining it, I'll send PRs.  If not, I can just fork it.  Thanks!

Joel

**Comment by biocomp** [comment]
Send the PRs, I'll try to take a look.
Thanks!

**Comment by joelwetzel** [comment]
Thanks!  Although, just in case this already exists and I don't need to build it:  is there any way, in a test, to provision a mock device that has more than one capability?  For example a dimmer device usually implements both Switch and SwitchLevel.

From looking at your examples, I've seen that to make a mock device with just one capability, I can do something like this:

> def dimmerDevice = getDevice(new DeviceInputValueFactory(SwitchLevel, 'SwitchLevel')
            .makeInputObject('n', 't',  DefaultAndUserValues.empty(), false))

But it seems that DeviceInputValueFactory can't accept multiple capabilities.  I've looked at the source and think I can extend it if I need to.

Anyway, thanks for the project!  It's super cool.

**Comment by biocomp** [comment]
Glad you find it useful )
Yeah, I don't think there's something like that, and you'd need to add your implementation.
