### ISSUE TITLE
Is the ADO submodule necessary?

### ISSUE THREAD

**Issue by joelwetzel** [biocomp/hubitat_ci#49]
Currently the .gitmodules file contains this submodule:

>[submodule "buildSrc/src/main/groovy/biocomp/HubitatCi"]
	path = buildSrc/src/main/groovy/biocomp/HubitatCi
	url = https://biocomp.visualstudio.com/DefaultCollection/HubitatStuff/_git/HubitatCi

Is this necessary?  The ADO project is locked down, so it throws an error if git tries to pull it.

**Comment by biocomp** [comment]
Hmm, I guess it isn't. Do you want to try to remove it and see what happens? )

**Comment by joelwetzel** [comment]
Yep! Thanks, I’ll remove it in one of my next PRs.
